[global]
api_key = "han1234"
admin_username = "admin"
admin_password = "admin"

[sora]
base_url = "https://sora.chatgpt.com/backend"
timeout = 120
max_retries = 3
poll_interval = 2.5
max_poll_attempts = 600

[server]
host = "0.0.0.0"
port = 8000

[debug]
enabled = false
log_requests = true
log_responses = true
mask_token = true

[cache]
timeout = 600
base_url = "http://127.0.0.1:8000"

[generation]
image_timeout = 300
video_timeout = 1500

[admin]
error_ban_threshold = 3

[proxy]
proxy_enabled = true
proxy_url = "socks5://warp:1080"

[watermark_free]
watermark_free_enabled = false

[video_length]
default_length = "10s"

[video_length.lengths]
10s = 300
15s = 450
